### ISSUE TITLE
Merging options and default options

### ISSUE THREAD

**Issue by witzawitz** [linslin/Yii2-Curl#11]
The order of merging this two arrays should be changed.
https://github.com/linslin/Yii2-Curl/blob/master/Curl.php#L246
```
return $this->_options + $this->_defaultOptions;
```

**Comment by witzawitz** [comment]
I've created pull request.
https://github.com/linslin/Yii2-Curl/pull/12

**Comment by witzawitz** [comment]
Though, there is trick using '+' when concating arrays. Maybe it will more correctly to use one array for storing options and directly overwrite its values.

**Comment by linslin** [comment]
Already fixed: https://github.com/linslin/Yii2-Curl/pull/7

Please don't push into master.

**Comment by witzawitz** [comment]
OK. Sorry for the duplicate.
When the release will be ready?

**Comment by linslin** [comment]
No problem. Just keep reporting issues. It's released since yesterday. HF :+1:
