### ISSUE TITLE
how to do this by yii2-curl

### ISSUE THREAD

**Issue by djfly** [linslin/Yii2-Curl#14]
how to do this by yii2-curl
`````
curl -XPUT 'localhost:9200/customer/external/1?pretty' -d '
{
  "name": "John Doe"
}'
````

**Comment by linslin** [comment]
//Init curl
        $curl = new curl\Curl();

        //post http://example.com/
        $response = $curl->setOption(
                CURLOPT_POSTFIELDS, 
                http_build_query(array(
                    'name' => 'John Doe'
                )
            ))
            ->put('http://localhost:9200/customer/external/1?pretty');

**Comment by linslin** [comment]
This information will cost you a star on my repo? :)

**Comment by djfly** [comment]
thanks
