### ISSUE TITLE
response always is empty string

### ISSUE THREAD

**Issue by TomassunGitHub** [linslin/Yii2-Curl#15]
in the version 1.0.3, the response always is empty string; when debug, the`CURLOPT_WRITEFUNCTION` not run

```php
$this->setOption(CURLOPT_WRITEFUNCTION, function ($curl, $data) use (&$body) {
    $body .= $data;
    return mb_strlen($data, '8bit');
});
```

but modify the function `getOptions` to version 1.0.2, is work

```php
public function getOptions()
 {
     return $this->_defaultOptions + $this->_options;
 }
```

myCurl version, my code use ssl

```php
$ php -r 'var_dump( curl_version());'
array(9) {
  'version_number' =>
  int(465408)
  'age' =>
  int(3)
  'features' =>
  int(50813)
  'ssl_version_number' =>
  int(0)
  'version' =>
  string(6) "7.26.0"
  'host' =>
  string(19) "x86_64-pc-linux-gnu"
  'ssl_version' =>
  string(14) "OpenSSL/1.0.1e"
  'libz_version' =>
  string(5) "1.2.7"
}
```

other Issue, when i want modify the `_defaultOptions`(eg:`CURLOPT_CONNECTTIMEOUT`),no way.

**Comment by linslin** [comment]
Thanks for Reporting. I will take a look on it.

**Comment by linslin** [comment]
Hey, I will Check this nett Week. Cheers

**Comment by linslin** [comment]
So, first of all: You cannot override `CURLOPT_WRITEFUNCTION` via `$curl->setOption();` right now. I promise, there is no need to override this function right now. Please update to `linslin/yii2-curl 1.0.4` which will be released today and tell me if it work for you now. 

Hint for CURLOPT_CONNECTTIMEOUT: 
````
        //Init curl
        $curl = new curl\Curl();


        echo $curl
            ->setOption(CURLOPT_CONNECTTIMEOUT, 30)
            ->get('http://example.com/');
```
Tested it right now with `1.0.3` and `1.0.4`and it works fine. Please run `composer update` to install a new version.
