### ISSUE TITLE
Result in sts output

### ISSUE THREAD

**Issue by taxist08** [linslin/Yii2-Curl#16]
Hi friend!
I tray you extensions and have result in standart output (display)
use linslin\yii2\curl;

$c = new curl\Curl();
$v = $c->get('https://github.com/linslin/Yii2-Curl/issues/new');

I'm need save content in variable.

**Comment by linslin** [comment]
This is a default curl behavior. Check http://php.net/manual/de/function.curl-setopt.php and set "CURLOPT_RETURNTRANSFER". Cheers
