### ISSUE TITLE
为什么原来程序正常，现在不通了

### ISSUE THREAD

**Issue by y284663247** [linslin/Yii2-Curl#17]
//Init curl
        $curl = new curl\Curl();

        //get http://example.com/
        $response = $curl->get('http://example.com/');

为什么得到的$response是个空串啊，

{"reason":"短信发送成功","result":{"count":1,"fee":1,"sid":1754675453},"error_code":0}string(0) ""
string(0) ""
这个是我返回的内容，下面的我的程序，原来都没有问题的程序啊，今天不通了
$curl = new Curl();
        $result = $curl->get($getUrl,true);

**Comment by linslin** [comment]
English please.
