### ISSUE TITLE
Getting errors from failed requests

### ISSUE THREAD

**Issue by Tomino2112** [linslin/Yii2-Curl#21]
At the moment, there is no easy way to get errors from failed requests. For example our request fails, with code 400 and body:

`{"email": ["Email is already in use"]}`

But return from your `_httpRequest()` in case of 400 error is simply false;

So we have to go and get the response, BUT the response is not being JSON decoded, because you have the `$raw` check only on successful request. 

I would fix it like this:

```
...
//retrieve response code
$this->responseCode = curl_getinfo($curl, CURLINFO_HTTP_CODE);
$this->response = $raw ? $this->response : Json::decode($body);
...
```

```
...
//check responseCode and return data/status
        if ($this->responseCode >= 200 && $this->responseCode < 300) { // all between 200 && 300 is successful
            return true;
        } elseif ($this->responseCode >= 400 && $this->responseCode <= 510) { // client and server errors return false.
            return false;
        } else { //any other status code or custom codes
            return true;
        }
...
```

I dont see much point returning the request result only in case its successful and its not HEAD. Just rather keep it consistent and have the function return boolean, and the developer to go for `$curl->response directly`

**Comment by linslin** [comment]
Hey @Tomino2112 ,

many thanks for you report. I totally agree to your use-case. I will check it soon and implement a nice behavior to make this feature work fine. Version 1.0.5 is coming in the next days and this will definitly be a part of it.

**Comment by Tomino2112** [comment]
@linslin No prob, thanks for considering the suggestion

**Comment by linslin** [comment]
@Tomino2112, in Version 1.0.5 (which probably will be released today) it is fixed right now: You can retrieve `body` data on any HTTP-Status now.
