### ISSUE TITLE
Https

### ISSUE THREAD

**Issue by vasudevan242** [linslin/Yii2-Curl#24]
How to handle the Https API's..? 
curl request failed: SSL certificate problem: unable to get local issuer certificate

**Comment by linslin** [comment]
Hey,

you need to configure your certificate in `curl.cainfo="<pathToCert>"` && `openssl.cafile="<pathToCert>"`in your `php.ini`. Do not forget to call your ressource via `https`. Do not set `CURLOPT_SSL_VERIFYPEER ` to 0, because it opens a gate MITM attacks.
