### ISSUE TITLE
Bug in setOption method

### ISSUE THREAD

**Issue by bogdaniy** [linslin/Yii2-Curl#30]
When I set some curl params using setOption method and call reset method, some params(set by me) doesn't reloads, because setOption method has not strict check (in_array https://secure.php.net/manual/ru/function.in-array.php#106319) and it goes to defaultParams . Good idea is to make more strict check with in_array strict param or replace it with isset function.

**Comment by linslin** [comment]
Hey @bogdaniy,

thanks for your response. I understand, Could you add some codes? Expecially your custom option set by `setOption($key, $value)`?

**Comment by bogdaniy** [comment]
Code
`$curl = new Curl();
        var_dump($curl->getOption(CURLOPT_CUSTOMREQUEST));
        $curl->setOption(CURLOPT_CUSTOMREQUEST, 'POST');
        $curl->reset();
        var_dump($curl->getOption(CURLOPT_CUSTOMREQUEST));`
Result
`bool(false)
string(4) "POST"`

**Comment by vasadibt** [comment]
I think the problem is in 'vendor/linslin/yii2-curl/Curl.php' on line 154

Original code:
if (in_array($key, $this->_defaultOptions) && $key !== CURLOPT_WRITEFUNCTION) {

My temporary solution:
if (array_key_exists($key, $this->_defaultOptions) && $key !== CURLOPT_WRITEFUNCTION) {

**Comment by linslin** [comment]
Thanks m8s
