### ISSUE TITLE
curl request failed: SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by ak868308** [linslin/Yii2-Curl#35]
I am unable to know why the extension shows this error "curl request failed: SSL certificate problem: self signed certificate in certificate chain" whenever I want to try to initiate https request like "https://test.payu.in/_payment" 
Please know what I will do if it necessary to go with https.
I already tried by setting the option CURLOPT_SSL_VERIFYPEER but it is not working... showing same error 
My curl is :  linslin\yii2\curl\Curl::_httpRequest('POST', 'https://test.payu.in/_payment', true)

this is my code :
$curl = new Curl();
                    $curl->setOption(
                        CURLOPT_POSTFIELDS,
                            CURLOPT_SSL_VERIFYPEER,
                        http_build_query([
                        $payu->hashstring()
                        ])
                    )->post($payu->payment_url);

Thanks is advance

**Comment by linslin** [comment]
Please take a look at this issue: https://github.com/linslin/Yii2-Curl/issues/10
