### ISSUE TITLE
How to execute GET-request with params?

### ISSUE THREAD

**Issue by RusNimex** [linslin/Yii2-Curl#40]
I need to run the following GET-request:

`curl --request GET \`
 `--url 'https://usX.api.mailchimp.com/3.0/campaigns' \`
 `--user 'anystring:apikey' \`
 `--include`

**Comment by linslin** [comment]
Hi @RusNimex,

HTTP-Basic-Auth is supported by cURL http://php.net/manual/de/function.curl-setopt.php.

```
$response = $curl->setOption(
                CURLOPT_USERPWD, 
                'anystring:apikey'
            ))->get('https://usX.api.mailchimp.com/3.0/campaigns');
```

Cheers, Lin
