### ISSUE TITLE
Can't get it to work via composer

### ISSUE THREAD

**Issue by gregsemyonov** [linslin/Yii2-Curl#46]
Hello I have yii2 basic project.
The extension was installed through composer.
Right after that I try as per example do the stuff:

use linslin\yii2\curl;
...
$curl = new curl\Curl();

And there is an exception "Class 'linslin\yii2\curl\Curl' not found".
It seems the Curl.php is in a right place as well as all the stuff inside composer.json. 
What goes wrong for me?
May be I need to execute some additional command in order to get the Curl into the classmap?

**Comment by linslin** [comment]
Have you installed other composer files? Does it work for those?

**Comment by gregsemyonov** [comment]
Sorry guys it was my mistake and it took me few hours to get a thing that I simply did not deploy all changes to my apache. The changes that I do in phpstorm are under autodeployment, but composer changes are not a subject for it. Yeap, I must be need to have a sleep.

**Comment by linslin** [comment]
=) cheers
