### ISSUE TITLE
Empty response when error code 302 redirect

### ISSUE THREAD

**Issue by WadeShuler** [linslin/Yii2-Curl#48]
The response should ALWAYS, always, always, return something. No matter what URL I try to "get", your '$curl->get()` should always return something.

    $curl = new curl\Curl();
    $hash = md5('fake@example.com');
    $response = $curl->get('https://www.gravatar.com/' . $hash . '.json');
    die('<pre>' . print_r($response, true) . '</pre>');
    return $response;

Note, the `die()` is being used for testing. This should work, and does work when I jump out early and use like `die('here');` just fine. So there are no issues with the route or controller or anything.

When I looked deeper using, `die('<pre>' . print_r($curl->statusCode, true) . '</pre>');`, it returned `302`, which is a redirect.

You should add `CURLOPT_FOLLOWLOCATION = true` to the default options, with the ability to change it if they need to.

I know that in order to get this to work:

    $response = $curl->get('https://www.gravatar.com/' . $hash . '.json');
    die($response->statusCode);    // <-- notice I am using $response not $curl!

Would take some recoding on your end. You would need to create an official release version to not break people's current versions. However, it should return the basic info:

    $response = $curl->get('https://www.gravatar.com/' . $hash . '.json');

$response should contain all the info I need in an array:

    [
        'data' => null, // the data from the get() function
        'statusCode' => 200,
        'errorCode' => 0,  // not sure what default with no error is?
        'headers => [],  // an array of the headers returned
        // maybe more here?
    ]

Then we would do this:

    public function actionGravatarProfile($email)
    {
        $curl = new curl\Curl();
        $hash = md5(trim($email));
        $response = $curl->get('https://www.gravatar.com/' . $hash . '.json');
        
        if ( $response->statusCode === 200 ) {
            // success
            return $response->data;
        } else if ($response->statusCode === 404 ) {
            // user not found
            die('User not found');  // crude but just example
        } else {
            // error
            die('Error was ' . $response->statusCode); // crude but just example
        }
    }

This will better allow us to handle errors, utilize Angular or jQuery if needed, etc.

For example, look at the jQuery AJAX function. It returns not just the data, but the status, headers, everything we need for post process handling.

---

However, without changing the code, in it's current form, we need to do this to follow redirects:

    $response = $curl->setOption(CURLOPT_FOLLOWLOCATION, true)->get('https://www.yoururlhere.com');

I hope you will consider at least setting follow location to true as your default options, and maybe even improving your logic handling as I laid out in this thread.

**Comment by linslin** [comment]
Thanks for your question. I've read it and I can deliver you some solution and suggestions.
First of all, as you already said, `linslin/curl` allows you to set `cURL PARAMS` on your own based on the simple wrapper
https://curl.haxx.se/. 

For example you can set `CURLOPT_FOLLOWLOCATION` if you need it. Making this a default option is not what this library 
is expected to deliver. Think about other users, who do not need that header. No need to fence users while they are able
to handle all the good cURL stuff on its own (if they need it). The `$_defaultOptions` variable in this library contains 
the smallest stack of needed cURL options to make a simple request. 

     $response = $curl
            ->setOption(CURLOPT_FOLLOWLOCATION , true)
            ->get('http://www.linslin.org');
            
Simplifying the response / callback like
 
     [
         'data' => null, // the data from the get() function
         'statusCode' => 200,
         'errorCode' => 0,  // not sure what default with no error is?
         'headers => [],  // an array of the headers returned
         // maybe more here?
     ]
 .. is not the way to handle all users requirements. Also jQuery/AngularJS and other libraries/frameworks which are 
 using `xhr` does not deliver that kind of response. For example, jQuery uses a own function provided by `xhr` like:
 
     success: function(res, status, xhr) { 
       alert(xhr.getResponseHeader("myHeader"));
     }

You will find more information about jQuery AJAX handling here: http://api.jquery.com/jQuery.ajax/. Remember, simplify is
a good way but its not good if you fence users. AngularJS & Angular2 provides this in nearly the same way.

I see your point "response headers". In that way I added a new attribute called `responseHeaders` in the current release
https://github.com/linslin/Yii2-Curl/releases/tag/1.0.11. This will give you a array of all response headers.

Let me show you how you will be able to access all the data you need without a simplified response:

     //request
     $curl = new curl\Curl();
     $response = $curl
            ->setOption(CURLOPT_FOLLOWLOCATION , true)
            ->get('http://www.linslin.org');
     
     //simplify
     $abstractResponse = [
         'data' => $response,
         'statusCode' => $curl->statusCode,
         'errorCode' => $curl->errorCode,
         'info => $curl->getInfo(),
         'headers => $curl->responseHeaders
     ]
     
I hope that will help you. Don't hesitate for more feature requests.

Cheers
Lin

**Comment by linslin** [comment]
> Empty response when error code 302 redirect

Well, this statement does mix two things. An errorCode is only provided if the cURL failed. An statusCode is provided if the request was successful or timed out. So, if you have an `statusCode = 302` an errorCode is not given.

Here you will find a list of all cURL errorCodes which are mapped with `linslin/curl` -> https://curl.haxx.se/libcurl/c/libcurl-errors.html. Please hint that errorCode `7` and `28` will give you an responseCode = 'timeout'.

Here you will find a list of all common http status codes https://en.wikipedia.org/wiki/List_of_HTTP_status_codes. You will be able to handle all codes with `linslin/curl`.

In that way you can handle a redirect by youself. This library will not handle responses on redirects because of its limitations. Think about a situation where many many many redirects happends in one call. This could end up in memory leak, abstract data handling & not wanted functionality. This library could handle it, but while this is a very uncommon situation you should handle it by your own. You could follow redirects by your own. In that way you are able to handle bodies & headers in your redirects:

        $response = $curl
            ->setOption(CURLOPT_FOLLOWLOCATION , false)
            ->get('http://www.linslin.org');

        switch ($curl->responseCode) {

            //follow redirect manually
            case 301:
            case 302:
            case 303:
                var_dump($response);
                $response = $curl->get($curl->responseHeaders['Location']);
                break;

            default:
                break;

        }
