### ISSUE TITLE
Getting text representation of error

### ISSUE THREAD

**Issue by janki1** [linslin/Yii2-Curl#49]
Hi, 

is any chance to get text representation of curl error not only error code ? 
Like using curl_error function ? 

Thanks for response.

**Comment by linslin** [comment]
Hey, thanks for your question.

We could implement a helper function which will return the text representation like http://php.net/manual/en/function.curl-strerror.php (https://curl.haxx.se/libcurl/c/curl_easy_strerror.html) based on https://curl.haxx.se/libcurl/c/libcurl-errors.html. 

While this library will not support localizations we will not implement custom text messages. We recommend to create a own helper which deliver you a error message based on the curl error code. In that way you could use localizations from third party libraries (e.g. Symfony2 translate, and so on).

**Comment by linslin** [comment]
@janki1 any feedback or suggestions?

**Comment by janki1** [comment]
Hi,

I am sorry I was out of internet for long time, because I was ill.

For me it would be enough if I were available to extract text from basic
curl error based on https://curl.haxx.se/libcurl/c/libcurl-errors.html
translations are welcome but not always suitable, or anybody can translate
error message in our system.



S pozdravom
Ján Úskoba
Tel.: 0948 083 758

2017-01-30 12:43 GMT+01:00 Nils Gajsek <notifications@github.com>:

**Comment by linslin** [comment]
Accepted, we will release this feature in the coming version.

**Comment by janki1** [comment]
Thanks a lot.

S pozdravom
Ján Úskoba
Tel.: 0948 083 758

2017-02-14 18:02 GMT+01:00 Nils Gajsek <notifications@github.com>:

**Comment by linslin** [comment]
`$curl->errorText` is now available in develop branch and will be released in version 1.1.0
