### ISSUE TITLE
responseHeaders with ':' truncated

### ISSUE THREAD

**Issue by ConstantinZinchenko** [linslin/Yii2-Curl#59]
In r 1.1.1 
line  
list ($key, $value) = explode(': ', $line);
_extractCurlHeaders

was changed to 
list ($key, $value) = explode(':', $line);

': ' with space -> ':' without space.
So header Location: http://foo.bar bocomes:
'Location'=>'http'

**Comment by linslin** [comment]
Great, thanks for this reporting. We will take a look on it in the next days!

**Comment by linslin** [comment]
Fixed in 1.1.2
