### ISSUE TITLE
Simultaneus requests

### ISSUE THREAD

**Issue by alvaropineda** [linslin/Yii2-Curl#62]
Hi,

Do you plan to add simultaneous requests ability to this extension? Something like MultiGet (https://github.com/Yaffle/MultiGet)

Thanks

**Comment by linslin** [comment]
I checked it multiple times and I'm still not sure about this request. The async handling of multiple request maybe  is something for another curl extension. Implementing this in *yii2-curl* will break it's simple architecture. Let me think about this some more time.

**Comment by neovash23** [comment]
What am I doing wrong here: 
`
$response = $curl
            ->setHeaders(CURLOPT_HTTPHEADER,[
                'Authorization' => 'Client-ID c5ddfba8180e164'
             ])
                    ->get('https://api.imgur.com/3/account/hndev2/albums/');
`

**Comment by linslin** [comment]
I finally came up to not implement this feature inside yii2-curl. I may going to write a new extension **yii2-multiCurl** to make it work. But this will take some time. I'm currently stucking in other projects. 

Anyway, thank you for your suggestion!
