### ISSUE TITLE
Not installed on PHP 5.6

### ISSUE THREAD

**Issue by RGump** [linslin/Yii2-Curl#63]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sebastian/recursion-context 3.0.0 requires php ^7.0 -> your PHP version (5.6.30) does not satisfy that requirement.
    - sebastian/recursion-context 3.0.0 requires php ^7.0 -> your PHP version (5.6.30) does not satisfy that requirement.
    - sebastian/recursion-context 3.0.0 requires php ^7.0 -> your PHP version (5.6.30) does not satisfy that requirement.
    - Installation request for sebastian/recursion-context (locked at 3.0.0) -> satisfiable by sebastian/recursion-context[3.0.0].

**Comment by linslin** [comment]
Testet it. It does works fine with PHP5.6 over here. `recursion-context` is not a part of `yii2-curl`. Please check your dependencies carefully.
