### ISSUE TITLE
How to post with Authorization as header?

### ISSUE THREAD

**Issue by neovash23** [linslin/Yii2-Curl#66]
What am I doing wrong here:

`
$response = $curl
 ->setHeaders(CURLOPT_HTTPHEADER,[ 'Authorization' => 'Client-ID c5ddfba8180e164' ]) 
->get('https://api.imgur.com/3/account/hndev2/albums/');
`

**Comment by linslin** [comment]
`$response = $curl->setHeaders([ 'Authorization' => 'Client-ID c5ddfba8180e164' ])
                              ->get('https://api.imgur.com/3/account/hndev2/albums/');`
