### ISSUE TITLE
Do not reinitialize curl resource. Make several request with the same session/cookies.

### ISSUE THREAD

**Issue by ODY90** [linslin/Yii2-Curl#67]
I need to login on site and make several request as logined user. But for each request method [_httpRequest ](https://github.com/linslin/Yii2-Curl/blob/master/Curl.php#L582) make curl_init($this->getUrl()), so for each request i am new user.
My code:
```php
$curl
    ->setOption(CURLOPT_COOKIESESSION, 1)
    ->setOption(CURLOPT_COOKIEJAR, '/tmp/cookies.txt')
    ->setPostParams($loginParams)
    ->post(LOGIN_URL);
```
```php
$curl->setPostParams($anotherParams)->post(ANOTHER_URL);
```
After first request i am loginned, all good. On second request i got error that i am not logined...

I porpose make some changes to [_httpRequest ](https://github.com/linslin/Yii2-Curl/blob/master/Curl.php#L582) method:
replace line [603](https://github.com/linslin/Yii2-Curl/blob/master/Curl.php#L603) 
to 
```php
if ($this->curl === null) {
    $this->curl = curl_init();
}
curl_setopt($this->curl, CURLOPT_URL, $this->getUrl());
```

**Comment by linslin** [comment]
Thanks for your request. We gonna check this in the next 2 Weeks. We are currently stucking in other projects.

Sorry, please hang on.

**Comment by linslin** [comment]
@ODY90 we checked this request carefully but we did not found any lacks inside the currently implemented logic. Your options:

```
$curl
    ->setOption(CURLOPT_COOKIESESSION, 1)
    ->setOption(CURLOPT_COOKIEJAR, '/tmp/cookies.txt')
    ->setPostParams($loginParams)
    ->post(LOGIN_URL);
```
... will be set on each new request, even when `curl_init()` is initialized again on each request. Maybe we are wrong but by reffering this https://stackoverflow.com/questions/30760213/save-cookies-between-two-curl-requests you should be able to handle your cookie session by using `CURLOPT_*` yourself. If not, please create a full qualyfied example of what is not working.

Thank you
Lin

**Comment by linslin** [comment]
@ODY90 any feedback?

**Comment by linslin** [comment]
@ODY90 we going to close this issue. Once you provide some feedback we will reopen it.
