### ISSUE TITLE
Issue Server Response not get

### ISSUE THREAD

**Issue by bluegaurav** [linslin/Yii2-Curl#69]
I have request to server using following code 
`$response = $curl
                    ->setHeaders(['accept' => 'application/json'])
                    ->setPostParams($parameters)
                    ->post($url);`
After this i have print  curl  Information
`$curl->getInfo()`
It give me following response 

> Array
(
    [url] =>url is write but i have not share here
    [content_type] => 
    [http_code] => 0
    [header_size] => 0
    [request_size] => 250
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.013403
    [namelookup_time] => 0.012373
    [connect_time] => 0.012944
    [pretransfer_time] => 0.012975
    [size_upload] => 52
    [size_download] => 0
    [speed_download] => 0
    [speed_upload] => 3879
    [download_content_length] => -1
    [upload_content_length] => 52
    [starttransfer_time] => 0.013394
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => ip is write but i have not share here
    [certinfo] => Array
        (
        )
    [primary_port] => 80
    [local_ip] => 10.0.27.188
    [local_port] => 36376
)

**Comment by linslin** [comment]
Thanks for your report. What is your problem?

**Comment by linslin** [comment]
@bluegaurav please provide some feedback.
