### ISSUE TITLE
Not Getting latest version

### ISSUE THREAD

**Issue by buttflattery** [linslin/Yii2-Curl#70]
i am using `Yii2 v 2.0.15.1` and whenever i try to install the extension it always installs the v `1.0.3` which is too old and does not have the `setGetParms` function and hence I am unable to run the simplest `get` request example with parameters.

in `composer.json` i have `minimum-stability:stable`  what should I do that it updates to the latest version rather than the older.

**Comment by linslin** [comment]
Thanks for your request. Could you please add your composer.json file? Thanks

**Comment by tanmay20** [comment]
Here It is - 
{
    "name": "yiisoft/yii2-app-advanced",
    "description": "Yii 2 Advanced Project Template",
    "keywords": ["yii2", "framework", "advanced", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "~2.0.6",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0 || ~2.1.0",
        "kartik-v/yii2-widget-sidenav": "*",
        "kartik-v/yii2-widget-activeform": "@dev",
        "kartik-v/yii2-widget-datepicker": "@dev",
        "kartik-v/yii2-widgets": "*",
        "wbraganca/yii2-dynamicform": "dev-master",
        "kartik-v/yii2-grid": "@dev",
        "mpdf/mpdf": "@dev",
        "kartik-v/yii2-mpdf": "*",
        "linslin/yii2-curl": "*"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",
        "codeception/base": "^2.2.3",
        "codeception/verify": "~0.3.1"
    },
    "config": {
        "process-timeout": 1800
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ]
}

**Comment by linslin** [comment]
Try set a specific version:

`"linslin/yii2-curl": "1.2.1"`

After this run `composer install` or `composer update`.

**Comment by tanmay20** [comment]
By this i learned that I had to install php curl. I've done that and updated yii2-curl to 1.2.1. Issue is solved.

**Comment by linslin** [comment]
Glad to help ya.
