### ISSUE TITLE
Curl not giving me any response

### ISSUE THREAD

**Issue by faisal1208** [linslin/Yii2-Curl#72]
I am trying to use a GET method to carry of some data from the a URL. I am trying to get a code from a URL by following this [Zoho Link](https://www.zoho.com/projects/help/rest-api/get-tickets-api.html)

Below is my code 

    `$curl = new curl\Curl();
        $response = $curl->setGetParams([
            'scope' => 'ZohoBugTracker.projects.ALL,ZohoBugTracker.bugs.ALL',
            'client_id' => '1000',
            'response_type' => 'code',
            'access_type' => 'offline',
            'redirect_uri' => 'http://11.111.111.111:7000/api/oauth/zoho_auth',
        ])
            ->get('https://accounts.zoho.com/oauth/v2/auth');

        if ($curl->errorCode === null) {
            echo $response;
        } else {

            echo '<pre>';print_r($curl->errorCode);
        }
        exit();`

I am using POSTMAN for testing my API but all I see a empty screen. I have also put this question on [StackOverFlow](https://stackoverflow.com/questions/51360587/yii2-how-to-get-contents-of-a-url/51402469?noredirect=1#comment89800160_51402469).

Can anyone please help me out

**Comment by linslin** [comment]
ts working quite fine when you enable SSL and check the response code / response header to redirect to the userAuth form on Zuhu:

$curl = new Curl();

```
/** @var Curl $response */
$curl->setGetParams([
        'scope' => 'ZohoBugTracker.projects.ALL,ZohoBugTracker.bugs.ALL',
        'client_id' => '1000',
        'response_type' => 'code',
        'access_type' => 'offline',
        'redirect_uri' => 'http://11.111.111.111:7000/api/oauth/zoho_auth',
])->setOption(CURLOPT_SSL_VERIFYPEER, true)
    ->setOption(CURLOPT_SSL_VERIFYHOST, false)
    ->setOption(CURLOPT_CAINFO, 'C:/Ampps/apache/conf/ssl_crt/cacert.pem')
    ->get('https://accounts.zoho.com/oauth/v2/auth');

$responseHeaders = $curl->responseHeaders;

if ($curl->responseCode === 302 && isset($responseHeaders['Location'])) {
    header("location: ".$responseHeaders['Location']);
    die();
}
```

I also answered this on stackoverflow. Feel free to accept this answer :).

**Comment by linslin** [comment]
Solved
