### ISSUE TITLE
I found a bug in your code - Wrong function patch()

### ISSUE THREAD

**Issue by vlad-004** [linslin/Yii2-Curl#73]
Hi, I found a bug in your code in the file Curl.php. Wrong function patch(). The function should  return $this->_httpRequest('**PATCH**',$raw);  Otherwise, I could not launch a request with the patch method. At now moment, you return $this->_httpRequest('**POST**',$raw);

**Comment by linslin** [comment]
Thanks for your report. I will check this in the next weeks.

**Comment by linslin** [comment]
@vlad-004 many thanks for your report. I fixed this issue in (1.3.0) - https://github.com/linslin/Yii2-Curl/releases/tag/1.3.0
