### ISSUE TITLE
Excluded `tests` directory from a composer package

### ISSUE THREAD

**Issue by ilyachase** [linslin/Yii2-Curl#78]
I faced a annoying thing:
<img width="864" alt="Снимок экрана 2019-05-12 в 12 37 08" src="https://user-images.githubusercontent.com/1961077/57579261-22017680-74b3-11e9-9da5-3be09ce1246a.png">

I think it is not necessary to include `tests` directory into package because it is only needed for development.

Also normalized composer.json using [composer-normalize](https://github.com/localheinz/composer-normalize).

Please review PR #77.

**Comment by linslin** [comment]
Thanks for this. Please create a pull request against develop branch.

**Comment by ilyachase** [comment]
Done. #79.

**Comment by linslin** [comment]
Still had no time to look on it. Please hang on!

**Comment by linslin** [comment]
Done in 1.4.0
