### ISSUE TITLE
Serialization of 'CURLFile' is not allowed

### ISSUE THREAD

**Issue by afunnydev** [linslin/Yii2-Curl#87]
Hello! I am using this extension to post a file to and endpoint during a CraftCMS Hook. To do so, I use a CURLFile in my body.

```
$headers = [
    'Authorization' => 'Bearer BlaBla',
];

$data = [
    'file' => new \CURLFile ( '/my/path', 'image/png', 'filename.png' ),
];

$curl = new curl\Curl();
$response = $curl->setRawPostData($data)->setHeaders($headers)->post($url);
```

Everything works well. However, when in development (i.e YII_DEBUG = true), I error with `Serialization of 'CURLFile' is not allowed` since the extension tries to serialize the CURLOPT_POSTFIELDS for debugging. I cannot redefine YII_DEBUG. Is there any way to opt out of debugging?

**Comment by nicolicioiul** [comment]
Confirmed on php 7.4

**Comment by linslin** [comment]
Hey guys,

thanks for your reporting. I will take a look on it in the next days.

**Comment by linslin** [comment]
Depending: https://github.com/mcustiel/phiremock-codeception-extension/issues/42 (For PHP 8 Update)

**Comment by linslin** [comment]
I will add a fix for this in the next version, which will also have PHP 8.0 Support. Meanwhile disable the debug mode in your `web/index.php`:

`defined('YII_DEBUG') or define('YII_DEBUG', false);`

**Comment by linslin** [comment]
Version 1.5.0 with PHP 8 support was just released: https://github.com/linslin/Yii2-Curl/releases/tag/1.5.0 

Thanks for your help!
